#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99

CONF="timecontrol"
PROG="/usr/bin/$CONF"
PIDFILE="/var/run/$CONF.pid"
INCLUDE_PATH="/var/etc/$CONF.include"

cleanup() {
	$("$PROG" stop) >/dev/null 2>&1
	rm -rf "$INCLUDE_PATH"
}

config_n_get() {
	local ret=$(uci -q get "${1}.${2}.${3}")
	echo "${ret:=$4}"
}

start_service() {
	local enabled=$(config_n_get "$CONF" "config" "enable" 0)

	if [ $enabled -ne 1 ]; then
		cleanup
		return 0
	fi

	mkdir -p "$(dirname "$INCLUDE_PATH")" && echo "/etc/init.d/$CONF reload" >"$INCLUDE_PATH"

	if [ -f "$PIDFILE" ]; then
		pid=$(cat "$PIDFILE" 2>/dev/null)
		if [ -n "$pid" ] && ! kill -0 "$pid" 2>/dev/null; then
			rm -f "$PIDFILE" >/dev/null 2>&1
		else
			$("$PROG" flush) >/dev/null 2>&1
		fi
	fi

	procd_open_instance "$CONF"
	procd_set_param command "$PROG"
	procd_set_param pidfile "$PIDFILE"
	procd_set_param respawn
	procd_close_instance
}

stop_service() {
	cleanup
}

service_triggers() {
	procd_add_reload_trigger "$CONF"
}
